spring.application.name=realestate-api
server.port=${PORT:8080}

springdoc.swagger-ui.path=/swagger-ui.html

# Neon Postgres — reads from env vars, falls back to local values
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-misty-mouse-aotbo1va-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_ft21QjkrcDTO}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:nihalgupta375@gmail.com}
spring.mail.password=${MAIL_PASSWORD:iqryfpwadxsxnwmy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.notification.email=${NOTIFICATION_EMAIL:nihalgupta375@gmail.com}

spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.mail.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000