# ============================================================
#  Application
# ============================================================
spring.application.name=realestate-api
server.port=8080

# ============================================================
#  Swagger / OpenAPI (springdoc)
#  Once running:
#    Swagger UI  ->  http://localhost:8080/swagger-ui.html
#    OpenAPI JSON ->  http://localhost:8080/v3/api-docs
# ============================================================
springdoc.swagger-ui.path=/swagger-ui.html


# ============================================================
# Neon Postgres
spring.datasource.url=jdbc:postgresql://ep-misty-mouse-aotbo1va-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ft21QjkrcDTO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true